MODULE DIRECT_RADCAL
   USE PRECISION_PARAMETERS
   USE RADCAL_CALC
   USE RADCAL_VAR
   IMPLICIT NONE
CONTAINS
   SUBROUTINE INIT_DIRECT
      NPT = 1
      OMMIN = 50._EB
      OMMAX = 10000._EB
      TWALL = 1173.15_EB
      ALLOCATE(PARTIAL_PRESSURES_ATM(N_RADCAL_SPECIES,1),TEMP_GAS(1),SEGMENT_LENGTH_M(1),TOTAL_PRESSURE_ATM(1))
      SEGMENT_LENGTH_M = 0.1_EB
      CALL RCALLOC
      CALL INIT_RADCAL
   END SUBROUTINE INIT_DIRECT

   SUBROUTINE GET_DIRECT_KAPPA(X,T,P,KP,K10)
      REAL(EB), INTENT(IN) :: X(5), T, P
      REAL(EB), INTENT(OUT) :: KP, K10
      REAL(EB) :: RADIANCE, TRANSMISSIVITY
      PARTIAL_PRESSURES_ATM = 0._EB
      PARTIAL_PRESSURES_ATM(I_CO2,1) = X(1)*P
      PARTIAL_PRESSURES_ATM(I_H2O,1) = X(2)*P
      PARTIAL_PRESSURES_ATM(I_CO,1) = X(3)*P
      PARTIAL_PRESSURES_ATM(I_FV,1) = X(4)
      PARTIAL_PRESSURES_ATM(I_C2H4,1) = X(5)*P
      PARTIAL_PRESSURES_ATM(I_N2,1) = (1._EB-SUM(X((/1,2,3,5/))))*P
      TEMP_GAS = T
      TOTAL_PRESSURE_ATM = P
      CALL SUB_RADCAL(K10,KP,RADIANCE,TRANSMISSIVITY)
   END SUBROUTINE GET_DIRECT_KAPPA

   SUBROUTINE CLOSE_DIRECT
      CALL RCDEALLOC2
      CALL RCDEALLOC
      DEALLOCATE(PARTIAL_PRESSURES_ATM,TEMP_GAS,SEGMENT_LENGTH_M,TOTAL_PRESSURE_ATM)
   END SUBROUTINE CLOSE_DIRECT
END MODULE DIRECT_RADCAL

PROGRAM GENERATE_DIRECT_VERIFICATION
   USE PRECISION_PARAMETERS
   USE DIRECT_RADCAL
   IMPLICIT NONE
   INTEGER :: N_KAPPA_X, N_KAPPA_C, N_RTMP, INPUT_UNIT, I, J, U
   INTEGER :: GAS_POSITION(4), ITARGET, ICO2, IH2O, ISOOT
   REAL(EB) :: KAPPA_X_MIN, KAPPA_X_MAX, KAPPA_C_MIN, KAPPA_C_MAX
   REAL(EB) :: RTMPMIN, RTMPMAX, P, LOG_X_FAC, LOG_C_FAC, KP, K10
   REAL(EB) :: X(5), T, TARGET_T, TARGET_CO2, TARGET_H2O
   REAL(EB), ALLOCATABLE :: GAS_AXIS(:), SOOT_AXIS(:), TEMP_AXIS(:)
   CHARACTER(16) :: SPECIES(5)
   CHARACTER(512) :: INPUT_FILE, OUTPUT_DIR, FILE_NAME
   NAMELIST /NN_INPUT/ KAPPA_X_MIN,KAPPA_X_MAX,KAPPA_C_MIN,KAPPA_C_MAX, &
                       N_KAPPA_X,N_KAPPA_C,RTMPMIN,RTMPMAX,N_RTMP,P

   KAPPA_X_MIN = 1.E-5_EB
   KAPPA_X_MAX = 1._EB
   KAPPA_C_MIN = 2.E-7_EB
   KAPPA_C_MAX = 0.2_EB
   N_KAPPA_X = 25
   N_KAPPA_C = 25
   RTMPMIN = 270._EB
   RTMPMAX = 2470._EB
   N_RTMP = 22
   P = 1._EB
   INPUT_FILE = '../RADCAL_TRAINING_DATA_GENERATION/RADCAL_NN_TEST.IN'
   OUTPUT_DIR = '.'
   IF (COMMAND_ARGUMENT_COUNT()>=1) CALL GET_COMMAND_ARGUMENT(1,INPUT_FILE)
   IF (COMMAND_ARGUMENT_COUNT()>=2) CALL GET_COMMAND_ARGUMENT(2,OUTPUT_DIR)
   OPEN(NEWUNIT=INPUT_UNIT,FILE=TRIM(INPUT_FILE),STATUS='OLD',ACTION='READ')
   READ(INPUT_UNIT,NN_INPUT)
   CLOSE(INPUT_UNIT)

   ALLOCATE(GAS_AXIS(0:N_KAPPA_X-1),SOOT_AXIS(0:N_KAPPA_C-1),TEMP_AXIS(0:N_RTMP-1))
   LOG_X_FAC = LOG((KAPPA_X_MAX/KAPPA_X_MIN)**(1._EB/(N_KAPPA_X-2)))
   LOG_C_FAC = LOG((KAPPA_C_MAX/KAPPA_C_MIN)**(1._EB/(N_KAPPA_C-2)))
   DO I=0,N_KAPPA_X-1
      GAS_AXIS(I) = GRID_VALUE(I,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_X_FAC)
   ENDDO
   DO I=0,N_KAPPA_C-1
      SOOT_AXIS(I) = GRID_VALUE(I,N_KAPPA_C,KAPPA_C_MIN,KAPPA_C_MAX,LOG_C_FAC)
   ENDDO
   DO I=0,N_RTMP-1
      TEMP_AXIS(I) = RTMPMIN+I*(RTMPMAX-RTMPMIN)/(N_RTMP-1)
   ENDDO

   SPECIES = (/'CO2             ','H2O             ','CO              ','C2H4            ','SOOT            '/)
   GAS_POSITION = (/1,2,3,5/)
   TARGET_T = 1527._EB
   TARGET_CO2 = 8.1854673070690193E-2_EB
   TARGET_H2O = 4.9619476030029037E-2_EB
   ITARGET = MINLOC(ABS(TEMP_AXIS-TARGET_T),DIM=1)-1
   ICO2 = MINLOC(ABS(GAS_AXIS-TARGET_CO2),DIM=1)-1
   IH2O = MINLOC(ABS(GAS_AXIS-TARGET_H2O),DIM=1)-1
   ISOOT = MINLOC(ABS(SOOT_AXIS-1.E-5_EB),DIM=1)-1
   T = TEMP_AXIS(ITARGET)
   CALL INIT_DIRECT

   DO J=1,5
      FILE_NAME = TRIM(OUTPUT_DIR)//'/direct_'//TRIM(SPECIES(J))//'_planck.dat'
      OPEN(NEWUNIT=U,FILE=TRIM(FILE_NAME),STATUS='REPLACE',ACTION='WRITE')
      WRITE(U,'(A)') '# T_INDEX TEMPERATURE_K FRACTION KAPPA_PLANCK_CM-1'
      DO I=0,N_RTMP-1
         X = 0._EB
         IF (J<=4) THEN
            X(GAS_POSITION(J)) = 1._EB
         ELSE
            X(4) = SOOT_AXIS(ISOOT)
         ENDIF
         CALL GET_DIRECT_KAPPA(X,TEMP_AXIS(I),P,KP,K10)
         WRITE(U,'(I6,3(1X,ES16.8E3))') I,TEMP_AXIS(I),MAXVAL(X),REAL(KP,FB)
      ENDDO
      CLOSE(U)
   ENDDO

   DO J=1,5
      FILE_NAME = TRIM(OUTPUT_DIR)//'/direct_'//TRIM(SPECIES(J))//'_kappa10cm.dat'
      OPEN(NEWUNIT=U,FILE=TRIM(FILE_NAME),STATUS='REPLACE',ACTION='WRITE')
      WRITE(U,'(A,ES16.8E3)') '# TEMPERATURE_K=',T
      WRITE(U,'(A)') '# AXIS_INDEX FRACTION KAPPA_10CM_CM-1'
      IF (J<=4) THEN
         DO I=0,N_KAPPA_X-1
            X = 0._EB
            X(GAS_POSITION(J)) = GAS_AXIS(I)
            CALL GET_DIRECT_KAPPA(X,T,P,KP,K10)
            WRITE(U,'(I6,2(1X,ES16.8E3))') I,GAS_AXIS(I),REAL(K10,FB)
         ENDDO
      ELSE
         DO I=0,N_KAPPA_C-1
            X = 0._EB
            X(4) = SOOT_AXIS(I)
            CALL GET_DIRECT_KAPPA(X,T,P,KP,K10)
            WRITE(U,'(I6,2(1X,ES16.8E3))') I,SOOT_AXIS(I),REAL(K10,FB)
         ENDDO
      ENDIF
      CLOSE(U)
   ENDDO

   FILE_NAME = TRIM(OUTPUT_DIR)//'/direct_CO2_H2O_kappa10cm.dat'
   OPEN(NEWUNIT=U,FILE=TRIM(FILE_NAME),STATUS='REPLACE',ACTION='WRITE')
   WRITE(U,'(A,ES16.8E3)') '# TEMPERATURE_K=',T
   WRITE(U,'(A,ES16.8E3)') '# CO2=',GAS_AXIS(ICO2)
   WRITE(U,'(A)') '# H2O_INDEX H2O_MOLE_FRACTION KAPPA_10CM_CM-1'
   DO I=0,N_KAPPA_X-1
      X = 0._EB
      X(1) = GAS_AXIS(ICO2)
      X(2) = GAS_AXIS(I)
      IF (X(1)+X(2)>1._EB) CYCLE
      CALL GET_DIRECT_KAPPA(X,T,P,KP,K10)
      WRITE(U,'(I6,2(1X,ES16.8E3))') I,X(2),REAL(K10,FB)
   ENDDO
   CLOSE(U)

   FILE_NAME = TRIM(OUTPUT_DIR)//'/direct_CO2_H2O_SOOT_kappa10cm.dat'
   OPEN(NEWUNIT=U,FILE=TRIM(FILE_NAME),STATUS='REPLACE',ACTION='WRITE')
   WRITE(U,'(A,ES16.8E3)') '# TEMPERATURE_K=',T
   WRITE(U,'(A,ES16.8E3)') '# CO2=',GAS_AXIS(ICO2)
   WRITE(U,'(A,ES16.8E3)') '# H2O=',GAS_AXIS(IH2O)
   WRITE(U,'(A)') '# SOOT_INDEX SOOT_VOLUME_FRACTION KAPPA_10CM_CM-1'
   DO I=0,N_KAPPA_C-1
      X = 0._EB
      X(1) = GAS_AXIS(ICO2)
      X(2) = GAS_AXIS(IH2O)
      X(4) = SOOT_AXIS(I)
      CALL GET_DIRECT_KAPPA(X,T,P,KP,K10)
      WRITE(U,'(I6,2(1X,ES16.8E3))') I,X(4),REAL(K10,FB)
   ENDDO
   CLOSE(U)

   CALL CLOSE_DIRECT
   DEALLOCATE(GAS_AXIS,SOOT_AXIS,TEMP_AXIS)
CONTAINS
   REAL(EB) FUNCTION GRID_VALUE(I,N,XMIN,XMAX,LOG_FAC)
      INTEGER, INTENT(IN) :: I, N
      REAL(EB), INTENT(IN) :: XMIN, XMAX, LOG_FAC
      IF (I==0) THEN
         GRID_VALUE = 0._EB
      ELSEIF (I==N-1) THEN
         GRID_VALUE = XMAX
      ELSE
         GRID_VALUE = XMIN*EXP((I-1)*LOG_FAC)
      ENDIF
   END FUNCTION GRID_VALUE
END PROGRAM GENERATE_DIRECT_VERIFICATION
