MODULE RADCAL_NN
   USE PRECISION_PARAMETERS
   USE RADCAL_CALC
   USE RADCAL_VAR
   IMPLICIT NONE

CONTAINS

   SUBROUTINE INIT_NN
      NPT = 1
      OMMIN = 50._EB
      OMMAX = 10000._EB
      TWALL = 900._EB+273.15_EB
      ALLOCATE(PARTIAL_PRESSURES_ATM(N_RADCAL_SPECIES,1), TEMP_GAS(1), SEGMENT_LENGTH_M(1), TOTAL_PRESSURE_ATM(1))
      SEGMENT_LENGTH_M = 0.1_EB ! 10 cm
      CALL RCALLOC
      CALL INIT_RADCAL
   END SUBROUTINE INIT_NN

   SUBROUTINE GET_KAPPA(X,T,P,KAPPA_PLANCK,KAPPA_10CM)
      REAL(EB), INTENT(IN) :: X(5), T, P
      REAL(EB), INTENT(OUT) :: KAPPA_PLANCK, KAPPA_10CM
      REAL(EB) :: RADIANCE, TRANSMISSIVITY

      IF (MINVAL(X)<0._EB .OR. SUM(X((/1,2,3,5/)))>1._EB) ERROR STOP 'Invalid composition'
      PARTIAL_PRESSURES_ATM = 0._EB
      PARTIAL_PRESSURES_ATM(I_CO2,1) = X(1)*P
      PARTIAL_PRESSURES_ATM(I_H2O,1) = X(2)*P
      PARTIAL_PRESSURES_ATM(I_CO,1) = X(3)*P
      PARTIAL_PRESSURES_ATM(I_FV,1) = X(4)
      PARTIAL_PRESSURES_ATM(I_C2H4,1) = X(5)*P
      PARTIAL_PRESSURES_ATM(I_N2,1) = (1._EB-SUM(X((/1,2,3,5/))))*P
      TEMP_GAS = T
      TOTAL_PRESSURE_ATM = P
      CALL SUB_RADCAL(KAPPA_10CM,KAPPA_PLANCK,RADIANCE,TRANSMISSIVITY)
   END SUBROUTINE GET_KAPPA

   SUBROUTINE CLOSE_NN
      CALL RCDEALLOC2
      CALL RCDEALLOC
      DEALLOCATE(PARTIAL_PRESSURES_ATM, TEMP_GAS, SEGMENT_LENGTH_M, TOTAL_PRESSURE_ATM)
   END SUBROUTINE CLOSE_NN

END MODULE RADCAL_NN

PROGRAM RADCAL_NN_DATABASE
   USE ISO_FORTRAN_ENV, ONLY: INT32, INT64, OUTPUT_UNIT
   USE MPI
   USE PRECISION_PARAMETERS
   USE RADCAL_NN
   IMPLICIT NONE

   INTEGER :: N_KAPPA_X, N_KAPPA_C, N_RTMP
   REAL(EB) :: KAPPA_X_MIN, KAPPA_X_MAX, KAPPA_C_MIN, KAPPA_C_MAX, RTMPMIN, RTMPMAX
   INTEGER :: IT, I1, I2, I3, I4, I5, INPUT_UNIT, HEADER_UNIT, GAS_UNIT
   INTEGER :: MY_RANK, N_PROCS, IERR, KAPPA_HANDLE, STATUS_ARRAY(MPI_STATUS_SIZE)
   INTEGER :: BUFFER_INDEX
   INTEGER(KIND=MPI_OFFSET_KIND) :: FILE_OFFSET, FILE_SIZE
   INTEGER(INT32) :: GAS_INDEX(4)
   INTEGER(INT64) :: N_VALID_GAS, RECORD_START
   INTEGER(INT64), ALLOCATABLE :: N_VALID_I1(:), GAS_START_I1(:)
   REAL(FB), ALLOCATABLE :: KAPPA_BUFFER(:)
   REAL(EB) :: X(5), T, P, KP, K10
   REAL(EB) :: KAPPA_X_FAC, LOG_KAPPA_X_FAC, KAPPA_C_FAC, LOG_KAPPA_C_FAC
   CHARACTER(255) :: INPUT_FILE, OUTPUT_PREFIX
   CHARACTER(512) :: HEADER_FILE, GAS_FILE, KAPPA_FILE
   NAMELIST /NN_INPUT/ KAPPA_X_MIN, KAPPA_X_MAX, KAPPA_C_MIN, KAPPA_C_MAX, &
                       N_KAPPA_X, N_KAPPA_C, RTMPMIN, RTMPMAX, N_RTMP, P

   CALL MPI_INIT(IERR)
   CALL MPI_COMM_RANK(MPI_COMM_WORLD,MY_RANK,IERR)
   CALL MPI_COMM_SIZE(MPI_COMM_WORLD,N_PROCS,IERR)
   IF (N_PROCS>44) THEN
      IF (MY_RANK==0) WRITE(*,'(A,I0,A)') 'ERROR: ',N_PROCS,' MPI processes requested; maximum is 44.'
      CALL MPI_ABORT(MPI_COMM_WORLD,1,IERR)
   ENDIF

   KAPPA_X_MIN = 1.E-5_EB
   KAPPA_X_MAX = 1._EB
   KAPPA_C_MIN = 2.E-7_EB
   KAPPA_C_MAX = 0.2_EB
   N_KAPPA_X = 50
   N_KAPPA_C = 50
   RTMPMIN = 270._EB
   RTMPMAX = 2470._EB
   N_RTMP = 44
   P = 1._EB
   INPUT_FILE = ''
   OUTPUT_PREFIX = ''
   IF (MY_RANK==0) THEN
      READ(*,'(A)') INPUT_FILE
      READ(*,'(A)') OUTPUT_PREFIX
   ENDIF
   CALL MPI_BCAST(INPUT_FILE,LEN(INPUT_FILE),MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
   CALL MPI_BCAST(OUTPUT_PREFIX,LEN(OUTPUT_PREFIX),MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
   OPEN(NEWUNIT=INPUT_UNIT,FILE=TRIM(INPUT_FILE),STATUS='OLD',ACTION='READ')
   READ(INPUT_UNIT,NN_INPUT)
   CLOSE(INPUT_UNIT)
   IF (N_KAPPA_X<3 .OR. N_KAPPA_C<3 .OR. N_RTMP<2) THEN
      IF (MY_RANK==0) WRITE(*,'(A)') 'ERROR: composition grids must be at least 3.'
      CALL MPI_ABORT(MPI_COMM_WORLD,2,IERR)
   ENDIF
   IF (KAPPA_X_MIN<=0._EB .OR. KAPPA_C_MIN<=0._EB) THEN
      IF (MY_RANK==0) WRITE(*,'(A)') 'ERROR: log grid bounds must be positive.'
      CALL MPI_ABORT(MPI_COMM_WORLD,3,IERR)
   ENDIF
   KAPPA_X_FAC = (KAPPA_X_MAX/KAPPA_X_MIN)**(1._EB/(N_KAPPA_X-2))
   LOG_KAPPA_X_FAC = LOG(KAPPA_X_FAC)
   KAPPA_C_FAC = (KAPPA_C_MAX/KAPPA_C_MIN)**(1._EB/(N_KAPPA_C-2))
   LOG_KAPPA_C_FAC = LOG(KAPPA_C_FAC)

   ALLOCATE(N_VALID_I1(0:N_KAPPA_X-1),GAS_START_I1(0:N_KAPPA_X-1))
   N_VALID_I1 = 0_INT64
   DO I1=0,N_KAPPA_X-1
      X(1) = GRID_VALUE(I1,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
      DO I2=0,N_KAPPA_X-1
         X(2) = GRID_VALUE(I2,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
         DO I3=0,N_KAPPA_X-1
            X(3) = GRID_VALUE(I3,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
            DO I4=0,N_KAPPA_X-1
               X(5) = GRID_VALUE(I4,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
               IF (SUM(X((/1,2,3,5/)))<=1._EB) N_VALID_I1(I1) = N_VALID_I1(I1)+1_INT64
            ENDDO
         ENDDO
      ENDDO
   ENDDO
   GAS_START_I1(0) = 0_INT64
   DO I1=1,N_KAPPA_X-1
      GAS_START_I1(I1) = GAS_START_I1(I1-1)+N_VALID_I1(I1-1)
   ENDDO
   N_VALID_GAS = SUM(N_VALID_I1)

   HEADER_FILE = TRIM(OUTPUT_PREFIX)//'_header.txt'
   GAS_FILE = TRIM(OUTPUT_PREFIX)//'_valid_gas_indices.bin'
   KAPPA_FILE = TRIM(OUTPUT_PREFIX)//'_kappa.bin'
   IF (MY_RANK==0) THEN
      OPEN(NEWUNIT=HEADER_UNIT,FILE=TRIM(HEADER_FILE),STATUS='REPLACE',ACTION='WRITE')
      WRITE(HEADER_UNIT,'(A)') 'SOURCE_CONFIG_FILE='//TRIM(INPUT_FILE)
      WRITE(HEADER_UNIT,'(A)') 'PATH_LENGTH_M=0.1'
      WRITE(HEADER_UNIT,'(A)') 'WALL_TEMPERATURE_C=900 C'
      WRITE(HEADER_UNIT,'(A)') 'WAVENUMBER_MIN_CM-1=50'
      WRITE(HEADER_UNIT,'(A)') 'WAVENUMBER_MAX_CM-1=10000'
      WRITE(HEADER_UNIT,'(A)') 'BACKGROUND_SPECIES=N2'
      WRITE(HEADER_UNIT,'(A)') 'VALID_GAS_RULE=CO2+H2O+CO+C2H4<=1'
      WRITE(HEADER_UNIT,'(A)') 'TEMPERATURE_SPACING=LINEAR'
      WRITE(HEADER_UNIT,'(A)') 'GAS_AXIS_SPACING=ZERO_PLUS_LOG'
      WRITE(HEADER_UNIT,'(A)') 'SOOT_AXIS_SPACING=ZERO_PLUS_LOG'
      WRITE(HEADER_UNIT,'(A,ES24.16E3)') 'PRESSURE_ATM=',P
      WRITE(HEADER_UNIT,'(A,I0)') 'MPI_PROCESSES=',N_PROCS
      WRITE(HEADER_UNIT,'(A,I0)') 'N_TEMPERATURE=',N_RTMP
      WRITE(HEADER_UNIT,'(A,I0)') 'N_GAS_AXIS=',N_KAPPA_X
      WRITE(HEADER_UNIT,'(A,I0)') 'N_SOOT_AXIS=',N_KAPPA_C
      WRITE(HEADER_UNIT,'(A,I0)') 'N_VALID_GAS=',N_VALID_GAS
      WRITE(HEADER_UNIT,'(A,I0)') 'N_KAPPA_RECORDS=',N_VALID_GAS*INT(N_RTMP,INT64)*INT(N_KAPPA_C,INT64)
      WRITE(HEADER_UNIT,'(A)') 'GAS_INDEX_FILE='//TRIM(GAS_FILE)
      WRITE(HEADER_UNIT,'(A)') 'GAS_INDEX_RECORD=4_NATIVE_INT32:CO2,H2O,CO,C2H4'
      WRITE(HEADER_UNIT,'(A)') 'KAPPA_FILE='//TRIM(KAPPA_FILE)
      WRITE(HEADER_UNIT,'(A)') 'KAPPA_RECORD=2_NATIVE_FLOAT32:PLANCK_CM-1,KAPPA_10CM_CM-1'
      WRITE(HEADER_UNIT,'(A)') 'ORDER=TEMPERATURE_INDEX,VALID_GAS_INDEX,SOOT_INDEX'
      WRITE(HEADER_UNIT,'(A)') 'RECORD_INDEX=((T_INDEX*N_VALID_GAS)+GAS_INDEX)*N_SOOT_AXIS+SOOT_INDEX'
      WRITE(HEADER_UNIT,'(/A)') '[TEMPERATURE_K]'
      DO IT=0,N_RTMP-1
         T = RTMPMIN+IT*(RTMPMAX-RTMPMIN)/(N_RTMP-1)
         WRITE(HEADER_UNIT,'(I0,1X,ES24.16E3)') IT,T
      ENDDO
      WRITE(HEADER_UNIT,'(/A)') '[GAS_MOLE_FRACTION]'
      DO I1=0,N_KAPPA_X-1
         WRITE(HEADER_UNIT,'(I0,1X,ES24.16E3)') I1, &
            GRID_VALUE(I1,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
      ENDDO
      WRITE(HEAqDER_UNIT,'(/A)') '[SOOT_VOLUME_FRACTION]'
      DO I5=0,N_KAPPA_C-1
         WRITE(HEADER_UNIT,'(I0,1X,ES24.16E3)') I5, &
            GRID_VALUE(I5,N_KAPPA_C,KAPPA_C_MIN,KAPPA_C_MAX,LOG_KAPPA_C_FAC)
      ENDDO
      CLOSE(HEADER_UNIT)

      OPEN(NEWUNIT=GAS_UNIT,FILE=TRIM(GAS_FILE),STATUS='REPLACE',ACCESS='STREAM',FORM='UNFORMATTED')
      DO I1=0,N_KAPPA_X-1
         X(1) = GRID_VALUE(I1,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
         DO I2=0,N_KAPPA_X-1
            X(2) = GRID_VALUE(I2,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
            DO I3=0,N_KAPPA_X-1
               X(3) = GRID_VALUE(I3,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
               DO I4=0,N_KAPPA_X-1
                  X(5) = GRID_VALUE(I4,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
                  IF (SUM(X((/1,2,3,5/)))>1._EB) CYCLE
                  GAS_INDEX = INT((/I1,I2,I3,I4/),INT32)
                  WRITE(GAS_UNIT) GAS_INDEX
               ENDDO
            ENDDO
         ENDDO
      ENDDO
      CLOSE(GAS_UNIT)
   ENDIF
   CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)

   CALL MPI_FILE_OPEN(MPI_COMM_WORLD,TRIM(KAPPA_FILE),IOR(MPI_MODE_CREATE,MPI_MODE_WRONLY), &
      MPI_INFO_NULL,KAPPA_HANDLE,IERR)
   FILE_SIZE = INT(N_VALID_GAS*INT(N_RTMP,INT64)*INT(N_KAPPA_C,INT64)*2_INT64* &
      INT(STORAGE_SIZE(0._FB)/8,INT64),MPI_OFFSET_KIND)
   CALL MPI_FILE_SET_SIZE(KAPPA_HANDLE,FILE_SIZE,IERR)
   IF (MY_RANK<N_RTMP) CALL INIT_NN
   DO IT=MY_RANK,N_RTMP-1,N_PROCS
      T = RTMPMIN+IT*(RTMPMAX-RTMPMIN)/(N_RTMP-1)
      WRITE(*,'(A,I0,A,I0,A,I0,A,F8.2,A)') 'Rank ',MY_RANK,': temperature ',IT+1,' of ',N_RTMP,' (',T,' K)'
      FLUSH(OUTPUT_UNIT)
      DO I1=0,N_KAPPA_X-1
         WRITE(*,'(A,I0,A,I0,A,I0,A,F6.1,A)') '  Rank ',MY_RANK,': CO2 level ',I1+1,' of ',N_KAPPA_X, &
            ' -- ',100._EB*I1/N_KAPPA_X,'%'
         FLUSH(OUTPUT_UNIT)
         ALLOCATE(KAPPA_BUFFER(MAX(1,INT(2_INT64*INT(N_KAPPA_C,INT64)*N_VALID_I1(I1)))))
         BUFFER_INDEX = 0
         X(1) = GRID_VALUE(I1,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
         DO I2=0,N_KAPPA_X-1
            X(2) = GRID_VALUE(I2,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
            DO I3=0,N_KAPPA_X-1
               X(3) = GRID_VALUE(I3,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
               DO I4=0,N_KAPPA_X-1
                  X(5) = GRID_VALUE(I4,N_KAPPA_X,KAPPA_X_MIN,KAPPA_X_MAX,LOG_KAPPA_X_FAC)
                  IF (SUM(X((/1,2,3,5/)))>1._EB) CYCLE
                  DO I5=0,N_KAPPA_C-1
                     X(4) = GRID_VALUE(I5,N_KAPPA_C,KAPPA_C_MIN,KAPPA_C_MAX,LOG_KAPPA_C_FAC)
                     CALL GET_KAPPA(X,T,P,KP,K10)
                     BUFFER_INDEX = BUFFER_INDEX+1
                     KAPPA_BUFFER(BUFFER_INDEX) = REAL(KP,FB)
                     BUFFER_INDEX = BUFFER_INDEX+1
                     KAPPA_BUFFER(BUFFER_INDEX) = REAL(K10,FB)
                  ENDDO
               ENDDO
            ENDDO
         ENDDO
         RECORD_START = (INT(IT,INT64)*N_VALID_GAS+GAS_START_I1(I1))*INT(N_KAPPA_C,INT64)
         FILE_OFFSET = INT(RECORD_START*2_INT64*INT(STORAGE_SIZE(0._FB)/8,INT64),MPI_OFFSET_KIND)
         IF (BUFFER_INDEX>0) CALL MPI_FILE_WRITE_AT(KAPPA_HANDLE,FILE_OFFSET,KAPPA_BUFFER,BUFFER_INDEX, &
            MPI_REAL,STATUS_ARRAY,IERR)
         DEALLOCATE(KAPPA_BUFFER)
      ENDDO
      WRITE(*,'(A,I0,A)') '  Rank ',MY_RANK,': progress 100.0%'
      WRITE(*,'(A,I0,A,I0,A,I0)') 'Rank ',MY_RANK,': completed temperature ',IT+1,' of ',N_RTMP
      FLUSH(OUTPUT_UNIT)
   ENDDO
   IF (MY_RANK<N_RTMP) CALL CLOSE_NN
   CALL MPI_FILE_CLOSE(KAPPA_HANDLE,IERR)
   DEALLOCATE(N_VALID_I1,GAS_START_I1)
   CALL MPI_FINALIZE(IERR)

CONTAINS

   REAL(EB) FUNCTION GRID_VALUE(I,N,XMIN,XMAX,LOG_FAC)
      INTEGER, INTENT(IN) :: I, N
      REAL(EB), INTENT(IN) :: XMIN, XMAX, LOG_FAC
      IF (I==0) THEN
         GRID_VALUE = 0._EB
      ELSEIF (I==N-1) THEN
         GRID_VALUE = XMAX
      ELSE
         GRID_VALUE = XMIN*EXP((I-1)*LOG_FAC)
      ENDIF
   END FUNCTION GRID_VALUE

END PROGRAM RADCAL_NN_DATABASE
